console.log("***********")
console.log('***********')
console.log("    ***    ")
console.log("    ***    ")
console.log("    ***    ")
console.log("    ***    ")
console.log("    ***    ")
console.log('\n')
console.log("**********")
console.log("*        *")
console.log('**********')
console.log("   ****   ")
console.log("   ****   ")
console.log("   ****   ")
console.log("   ****   ")
console.log("   ****   ")
console.log("**********")
console.log("*        *")
console.log('**********')
console.log('\n')
console.log("======================================")
console.log("======          LAB 5           ======")
console.log("======================================")
